// Package bindings generates TypeScript frontend clients from command and
// event definitions. Output is deterministic and tied to the kernel API
// version.
package bindings

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"go.klarlabs.de/vitra/domain"
)

// Command describes one frontend-callable command for code generation.
// Input and Output are the Go types the command decodes and returns; nil
// means the shape is unknown and is typed as `unknown`. Void marks a command
// that returns nothing (null on the wire); it is typed as `void` and
// Output is ignored.
type Command struct {
	Name        domain.CommandName
	Description string
	Permission  domain.PermissionName
	Input       reflect.Type
	Output      reflect.Type
	Void        bool
}

// Untyped describes command definitions whose input and output types are
// unknown (plugin contributions, hand-written executors).
func Untyped(defs ...*domain.CommandDefinition) []Command {
	out := make([]Command, 0, len(defs))
	for _, d := range defs {
		if d == nil {
			continue
		}
		out = append(out, Command{Name: d.Name(), Description: d.Description(), Permission: d.Permission()})
	}
	return out
}

// GenerateTypeScript emits a TypeScript module with a typed client for
// commands and subscription helpers for events (plugin Contribution.Events /
// runtime channels). It fails if two commands map to the same method name or
// a type cannot be encoded as JSON.
func GenerateTypeScript(moduleName, kernelVersion string, commands []Command, events []domain.EventName) (string, error) {
	sorted := append([]Command(nil), commands...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	types := newTypeMapper()
	type method struct {
		cmd        Command
		name       string
		in, out    string
		inOptional bool
	}
	methods := make([]method, 0, len(sorted))
	seen := map[string]domain.CommandName{}
	for _, c := range sorted {
		name := tsMethodName(string(c.Name))
		if prev, dup := seen[name]; dup {
			return "", fmt.Errorf("commands %q and %q both generate method %s", prev, c.Name, name)
		}
		seen[name] = c.Name
		m := method{cmd: c, name: name, in: "unknown", out: "unknown", inOptional: true}
		if c.Input != nil {
			ts, err := types.tsType(c.Input)
			if err != nil {
				return "", fmt.Errorf("command %s input: %w", c.Name, err)
			}
			m.in = ts
			m.inOptional = isEmptyStruct(c.Input) || allFieldsOptional(c.Input)
		}
		if c.Void {
			m.out = "void"
		} else if c.Output != nil {
			ts, err := types.tsType(c.Output)
			if err != nil {
				return "", fmt.Errorf("command %s output: %w", c.Name, err)
			}
			m.out = ts
		}
		methods = append(methods, m)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by vitra bindings. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// kernel: %s\n", lineSafe(kernelVersion))
	fmt.Fprintf(&b, "// module: %s\n\n", lineSafe(moduleName))
	for _, decl := range types.declarations() {
		b.WriteString(decl + "\n\n")
	}
	b.WriteString("export type VitraInvoker = (command: string, input?: unknown, resourcePath?: string) => Promise<unknown>;\n")
	b.WriteString("export type VitraEventHandler = (payload: unknown) => void;\n")
	b.WriteString("export type VitraSubscriber = (event: string, handler: VitraEventHandler) => () => void;\n\n")
	b.WriteString("export interface VitraClient {\n")
	for _, m := range methods {
		doc := commentSafe(m.cmd.Description)
		if doc != "" {
			doc += " — "
		}
		fmt.Fprintf(&b, "  /** %srequires permission `%s` */\n", doc, commentSafe(string(m.cmd.Permission)))
		opt := ""
		if m.inOptional {
			opt = "?"
		}
		fmt.Fprintf(&b, "  %s(input%s: %s, resourcePath?: string): Promise<%s>;\n", propertyName(m.name), opt, m.in, m.out)
	}
	b.WriteString("}\n\n")
	b.WriteString("export function createClient(invoke: VitraInvoker): VitraClient {\n")
	b.WriteString("  return {\n")
	for _, m := range methods {
		cast := ""
		if m.out != "unknown" {
			cast = " as Promise<" + m.out + ">"
		}
		fmt.Fprintf(&b, "    %s: (input, resourcePath) => invoke(%s, input, resourcePath)%s,\n", propertyName(m.name), jsString(string(m.cmd.Name)), cast)
	}
	b.WriteString("  };\n}\n")

	evSorted := uniqueSortedEvents(events)
	if len(evSorted) > 0 {
		b.WriteString("\nexport interface VitraEvents {\n")
		for _, ev := range evSorted {
			fmt.Fprintf(&b, "  /** Subscribe to `%s` via vitra.on; returns an unsubscribe function. */\n", commentSafe(string(ev)))
			fmt.Fprintf(&b, "  %s(handler: VitraEventHandler): () => void;\n", propertyName(tsEventMethodName(string(ev))))
		}
		b.WriteString("}\n\n")
		b.WriteString("export function createEvents(on: VitraSubscriber): VitraEvents {\n")
		b.WriteString("  return {\n")
		for _, ev := range evSorted {
			fmt.Fprintf(&b, "    %s: (handler) => on(%s, handler),\n", propertyName(tsEventMethodName(string(ev))), jsString(string(ev)))
		}
		b.WriteString("  };\n}\n")
	}
	return b.String(), nil
}

func isEmptyStruct(t reflect.Type) bool {
	return t.Kind() == reflect.Struct && t.NumField() == 0
}

// allFieldsOptional reports whether t is a struct whose JSON fields are all
// optional (omitempty or omitzero), so the input itself may be omitted.
func allFieldsOptional(t reflect.Type) bool {
	if t.Kind() != reflect.Struct {
		return false
	}
	for i := range t.NumField() {
		f := t.Field(i)
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		if f.Anonymous && name == "" {
			ft := f.Type
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				if !allFieldsOptional(ft) {
					return false
				}
				continue
			}
		}
		if !f.IsExported() {
			continue
		}
		if !hasOpt(opts, "omitempty") && !hasOpt(opts, "omitzero") {
			return false
		}
	}
	return true
}

func uniqueSortedEvents(events []domain.EventName) []domain.EventName {
	seen := map[string]struct{}{}
	var out []domain.EventName
	for _, ev := range events {
		s := string(ev)
		if s == "" {
			continue
		}
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, ev)
	}
	sort.Slice(out, func(i, j int) bool {
		return string(out[i]) < string(out[j])
	})
	return out
}

func tsMethodName(command string) string {
	parts := strings.FieldsFunc(command, func(r rune) bool {
		return r == '.' || r == '-' || r == '_'
	})
	if len(parts) == 0 {
		return "invoke"
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(strings.ToLower(p[:1]) + p[1:])
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func tsEventMethodName(event string) string {
	m := tsMethodName(event)
	return "on" + strings.ToUpper(m[:1]) + m[1:]
}

var identifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// propertyName returns name as a TypeScript property key, quoting it when it
// is not a plain identifier.
func propertyName(name string) string {
	if identifier.MatchString(name) {
		return name
	}
	return jsString(name)
}

// jsString returns s as a JavaScript string literal. JSON string syntax is a
// subset of JavaScript's (and escapes U+2028/U+2029), unlike Go's %q, which
// can emit \U escapes JavaScript does not understand.
func jsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// commentSafe makes s safe inside a single-line /** */ comment.
func commentSafe(s string) string {
	s = strings.ReplaceAll(s, "*/", "*\\/")
	return strings.Join(strings.FieldsFunc(s, func(r rune) bool {
		return r == '\n' || r == '\r' || r == ' ' || r == ' '
	}), " ")
}

func lineSafe(s string) string { return commentSafe(s) }
