// Code generated by vitra bindings. DO NOT EDIT.
// kernel: 0.9.0
// module: vitra

export interface DialogOptions {
  title?: string;
  defaultPath?: string;
  filters?: FileFilter[] | null;
  multiple?: boolean;
}

export interface DragDropInput {
  id?: string;
  enabled?: boolean;
}

export interface FileFilter {
  name?: string;
  extensions?: string[] | null;
}

export interface MenuInput {
  items: MenuItem[] | null;
}

export interface MenuItem {
  id: string;
  label: string;
  menu?: string;
  shortcut?: string;
}

export interface MessageDialogInput {
  title?: string;
  message: string;
  kind?: string;
}

export interface NotificationInput {
  title?: string;
  body: string;
}

export interface OsInfo {
  os: string;
  arch: string;
  family: string;
  version?: string;
  locale?: string;
}

export interface ShortcutInput {
  accelerator: string;
  action: string;
}

export interface ShortcutRef {
  accelerator: string;
}

export interface TrayInput {
  tooltip?: string;
  items?: MenuItem[] | null;
}

export interface WindowAlwaysOnTopInput {
  id: string;
  alwaysOnTop: boolean;
}

export interface WindowChrome {
  Title: string;
  Width: number;
  Height: number;
  Maximized: boolean;
  Fullscreen: boolean;
  AlwaysOnTop: boolean;
  Minimized: boolean;
  Hidden: boolean;
  IconPath: string;
}

export interface WindowChromeInput {
  id: string;
  title?: string;
  width?: number;
  height?: number;
  maximized?: boolean;
  fullscreen?: boolean;
  alwaysOnTop?: boolean;
  minimized?: boolean;
  hidden?: boolean;
  iconPath?: string;
}

export interface WindowCreateInput {
  id: string;
  title?: string;
  path?: string;
  width?: number;
  height?: number;
}

export interface WindowCreated {
  id: string;
}

export interface WindowIconInput {
  id: string;
  iconPath: string;
}

export interface WindowRef {
  id: string;
}

export interface WindowSizeInput {
  id: string;
  width: number;
  height: number;
}

export interface WindowTitleInput {
  id: string;
  title: string;
}

export interface WriteFileInput {
  path: string;
  data: string;
}

export type VitraInvoker = (command: string, input?: unknown, resourcePath?: string) => Promise<unknown>;
export type VitraEventHandler = (payload: unknown) => void;
export type VitraSubscriber = (event: string, handler: VitraEventHandler) => () => void;

export interface VitraClient {
  /** Quit the application — requires permission `app.quit` */
  appQuit(input?: {}, resourcePath?: string): Promise<void>;
  /** Open a URL in the system browser — requires permission `browser.open` */
  browserOpen(input: string, resourcePath?: string): Promise<void>;
  /** Read the system clipboard — requires permission `clipboard.read` */
  clipboardRead(input?: {}, resourcePath?: string): Promise<string>;
  /** Write the system clipboard — requires permission `clipboard.write` */
  clipboardWrite(input: string, resourcePath?: string): Promise<void>;
  /** Show a native message or confirm dialog — requires permission `dialog.message` */
  dialogMessage(input: MessageDialogInput, resourcePath?: string): Promise<boolean>;
  /** Open file dialog — requires permission `dialog.open` */
  dialogOpen(input?: DialogOptions, resourcePath?: string): Promise<string[] | null>;
  /** Open directory dialog (optional title, defaultPath) — requires permission `dialog.openDirectory` */
  dialogOpenDirectory(input?: DialogOptions, resourcePath?: string): Promise<string>;
  /** Save file dialog — requires permission `dialog.save` */
  dialogSave(input?: DialogOptions, resourcePath?: string): Promise<string>;
  /** Enable or disable file drops on a window — requires permission `dragdrop.receive` */
  dragdropReceive(input?: DragDropInput, resourcePath?: string): Promise<void>;
  /** Read a file within grant scope — requires permission `fs.read` */
  fsRead(input: string, resourcePath?: string): Promise<string>;
  /** Write a file within grant scope — requires permission `fs.write` */
  fsWrite(input: WriteFileInput, resourcePath?: string): Promise<void>;
  /** Clear the application menu bar — requires permission `menu.set` */
  menuClear(input?: {}, resourcePath?: string): Promise<void>;
  /** Replace the application menu bar — requires permission `menu.set` */
  menuSet(input: MenuInput, resourcePath?: string): Promise<void>;
  /** Show a desktop notification — requires permission `notifications.show` */
  notificationsShow(input: NotificationInput, resourcePath?: string): Promise<void>;
  /** Read host OS/arch/locale — requires permission `os.info` */
  osInfo(input?: {}, resourcePath?: string): Promise<OsInfo>;
  /** Open a local path with the OS default handler — requires permission `path.open` */
  pathOpen(input: string, resourcePath?: string): Promise<void>;
  /** Register a global OS shortcut — requires permission `shortcut.register` */
  shortcutRegister(input: ShortcutInput, resourcePath?: string): Promise<void>;
  /** Unregister a global OS shortcut — requires permission `shortcut.register` */
  shortcutUnregister(input: ShortcutRef, resourcePath?: string): Promise<void>;
  /** Clear the system tray icon — requires permission `tray.set` */
  trayClear(input?: {}, resourcePath?: string): Promise<void>;
  /** Set the system tray icon and context menu — requires permission `tray.set` */
  traySet(input?: TrayInput, resourcePath?: string): Promise<void>;
  /** Resign key focus on an application window — requires permission `window.chrome` */
  windowBlur(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Apply window presentation (title, size, chrome) — requires permission `window.chrome` */
  windowChrome(input: WindowChromeInput, resourcePath?: string): Promise<void>;
  /** Close an application window — requires permission `window.close` */
  windowClose(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Open an application window — requires permission `window.create` */
  windowCreate(input: WindowCreateInput, resourcePath?: string): Promise<WindowCreated>;
  /** Raise and focus an application window — requires permission `window.chrome` */
  windowFocus(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Enter fullscreen for an application window — requires permission `window.chrome` */
  windowFullscreen(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Read window presentation (title, size, chrome) — requires permission `window.chrome` */
  windowGetChrome(input: WindowRef, resourcePath?: string): Promise<WindowChrome>;
  /** Hide an application window — requires permission `window.chrome` */
  windowHide(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Maximize an application window — requires permission `window.chrome` */
  windowMaximize(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Minimize an application window — requires permission `window.chrome` */
  windowMinimize(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Restore an application window from minimized/maximized/fullscreen — requires permission `window.chrome` */
  windowRestore(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Toggle always-on-top for an application window — requires permission `window.chrome` */
  windowSetAlwaysOnTop(input: WindowAlwaysOnTopInput, resourcePath?: string): Promise<void>;
  /** Set the icon of an application window — requires permission `window.chrome` */
  windowSetIcon(input: WindowIconInput, resourcePath?: string): Promise<void>;
  /** Set the size of an application window — requires permission `window.chrome` */
  windowSetSize(input: WindowSizeInput, resourcePath?: string): Promise<void>;
  /** Set the title of an application window — requires permission `window.chrome` */
  windowSetTitle(input: WindowTitleInput, resourcePath?: string): Promise<void>;
  /** Show an application window — requires permission `window.chrome` */
  windowShow(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Exit fullscreen for an application window — requires permission `window.chrome` */
  windowUnfullscreen(input: WindowRef, resourcePath?: string): Promise<void>;
  /** Restore an application window from maximized — requires permission `window.chrome` */
  windowUnmaximize(input: WindowRef, resourcePath?: string): Promise<void>;
}

export function createClient(invoke: VitraInvoker): VitraClient {
  return {
    appQuit: (input, resourcePath) => invoke("app.quit", input, resourcePath) as Promise<void>,
    browserOpen: (input, resourcePath) => invoke("browser.open", input, resourcePath) as Promise<void>,
    clipboardRead: (input, resourcePath) => invoke("clipboard.read", input, resourcePath) as Promise<string>,
    clipboardWrite: (input, resourcePath) => invoke("clipboard.write", input, resourcePath) as Promise<void>,
    dialogMessage: (input, resourcePath) => invoke("dialog.message", input, resourcePath) as Promise<boolean>,
    dialogOpen: (input, resourcePath) => invoke("dialog.open", input, resourcePath) as Promise<string[] | null>,
    dialogOpenDirectory: (input, resourcePath) => invoke("dialog.openDirectory", input, resourcePath) as Promise<string>,
    dialogSave: (input, resourcePath) => invoke("dialog.save", input, resourcePath) as Promise<string>,
    dragdropReceive: (input, resourcePath) => invoke("dragdrop.receive", input, resourcePath) as Promise<void>,
    fsRead: (input, resourcePath) => invoke("fs.read", input, resourcePath) as Promise<string>,
    fsWrite: (input, resourcePath) => invoke("fs.write", input, resourcePath) as Promise<void>,
    menuClear: (input, resourcePath) => invoke("menu.clear", input, resourcePath) as Promise<void>,
    menuSet: (input, resourcePath) => invoke("menu.set", input, resourcePath) as Promise<void>,
    notificationsShow: (input, resourcePath) => invoke("notifications.show", input, resourcePath) as Promise<void>,
    osInfo: (input, resourcePath) => invoke("os.info", input, resourcePath) as Promise<OsInfo>,
    pathOpen: (input, resourcePath) => invoke("path.open", input, resourcePath) as Promise<void>,
    shortcutRegister: (input, resourcePath) => invoke("shortcut.register", input, resourcePath) as Promise<void>,
    shortcutUnregister: (input, resourcePath) => invoke("shortcut.unregister", input, resourcePath) as Promise<void>,
    trayClear: (input, resourcePath) => invoke("tray.clear", input, resourcePath) as Promise<void>,
    traySet: (input, resourcePath) => invoke("tray.set", input, resourcePath) as Promise<void>,
    windowBlur: (input, resourcePath) => invoke("window.blur", input, resourcePath) as Promise<void>,
    windowChrome: (input, resourcePath) => invoke("window.chrome", input, resourcePath) as Promise<void>,
    windowClose: (input, resourcePath) => invoke("window.close", input, resourcePath) as Promise<void>,
    windowCreate: (input, resourcePath) => invoke("window.create", input, resourcePath) as Promise<WindowCreated>,
    windowFocus: (input, resourcePath) => invoke("window.focus", input, resourcePath) as Promise<void>,
    windowFullscreen: (input, resourcePath) => invoke("window.fullscreen", input, resourcePath) as Promise<void>,
    windowGetChrome: (input, resourcePath) => invoke("window.getChrome", input, resourcePath) as Promise<WindowChrome>,
    windowHide: (input, resourcePath) => invoke("window.hide", input, resourcePath) as Promise<void>,
    windowMaximize: (input, resourcePath) => invoke("window.maximize", input, resourcePath) as Promise<void>,
    windowMinimize: (input, resourcePath) => invoke("window.minimize", input, resourcePath) as Promise<void>,
    windowRestore: (input, resourcePath) => invoke("window.restore", input, resourcePath) as Promise<void>,
    windowSetAlwaysOnTop: (input, resourcePath) => invoke("window.setAlwaysOnTop", input, resourcePath) as Promise<void>,
    windowSetIcon: (input, resourcePath) => invoke("window.setIcon", input, resourcePath) as Promise<void>,
    windowSetSize: (input, resourcePath) => invoke("window.setSize", input, resourcePath) as Promise<void>,
    windowSetTitle: (input, resourcePath) => invoke("window.setTitle", input, resourcePath) as Promise<void>,
    windowShow: (input, resourcePath) => invoke("window.show", input, resourcePath) as Promise<void>,
    windowUnfullscreen: (input, resourcePath) => invoke("window.unfullscreen", input, resourcePath) as Promise<void>,
    windowUnmaximize: (input, resourcePath) => invoke("window.unmaximize", input, resourcePath) as Promise<void>,
  };
}

export interface VitraEvents {
  /** Subscribe to `deeplink.open` via vitra.on; returns an unsubscribe function. */
  onDeeplinkOpen(handler: VitraEventHandler): () => void;
  /** Subscribe to `dragdrop.drop` via vitra.on; returns an unsubscribe function. */
  onDragdropDrop(handler: VitraEventHandler): () => void;
  /** Subscribe to `fs.changed` via vitra.on; returns an unsubscribe function. */
  onFsChanged(handler: VitraEventHandler): () => void;
  /** Subscribe to `menu.action` via vitra.on; returns an unsubscribe function. */
  onMenuAction(handler: VitraEventHandler): () => void;
  /** Subscribe to `shortcut.action` via vitra.on; returns an unsubscribe function. */
  onShortcutAction(handler: VitraEventHandler): () => void;
  /** Subscribe to `tray.action` via vitra.on; returns an unsubscribe function. */
  onTrayAction(handler: VitraEventHandler): () => void;
}

export function createEvents(on: VitraSubscriber): VitraEvents {
  return {
    onDeeplinkOpen: (handler) => on("deeplink.open", handler),
    onDragdropDrop: (handler) => on("dragdrop.drop", handler),
    onFsChanged: (handler) => on("fs.changed", handler),
    onMenuAction: (handler) => on("menu.action", handler),
    onShortcutAction: (handler) => on("shortcut.action", handler),
    onTrayAction: (handler) => on("tray.action", handler),
  };
}
