version: "2"

run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go.klarlabs.de/vitra
