package packaging

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// BuildNSISDir stages a Windows payload and writes installer.nsi for NSIS.
// Producing a final setup .exe still requires makensis (or VITRA_MAKENSIS);
// this layout is the portable intermediate that tool consumes.
func BuildNSISDir(spec Spec, binaryPath, outDir string) (Artifact, error) {
	if err := spec.Validate(); err != nil {
		return Artifact{}, err
	}
	if !hasTarget(spec, TargetWindowsNSIS) && !hasTarget(spec, TargetWindowsDir) {
		return Artifact{}, fmt.Errorf("BuildNSISDir requires target %s or %s", TargetWindowsNSIS, TargetWindowsDir)
	}
	art, err := StageWindows(withWindowsTargets(spec, TargetWindowsNSIS), binaryPath, outDir)
	if err != nil {
		return Artifact{}, err
	}
	safeName := sanitizeFileName(spec.Name)
	exeName := safeName
	if !strings.HasSuffix(strings.ToLower(exeName), ".exe") {
		exeName += ".exe"
	}
	outInstaller := safeName + "-setup.exe"
	nsi := fmt.Sprintf(`; Generated by vitra package — fold with makensis (or VITRA_MAKENSIS).
!define PRODUCT_NAME "%s"
!define PRODUCT_VERSION "%s"
!define PRODUCT_PUBLISHER "%s"
!define PRODUCT_APPID "%s"
!define PRODUCT_EXE "%s"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "%s"
InstallDir "$LOCALAPPDATA\${PRODUCT_NAME}"
RequestExecutionLevel user
SetCompressor /SOLID lzma

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  File "bin\${PRODUCT_EXE}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_EXE}"
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\${PRODUCT_EXE}"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}.lnk"
  RMDir "$INSTDIR"
SectionEnd
`, nsisEscape(spec.Name), nsisEscape(spec.Version), nsisEscape(spec.Name),
		nsisEscape(spec.AppID), exeName, outInstaller)
	if err := os.WriteFile(filepath.Join(outDir, "installer.nsi"), []byte(nsi), 0o644); err != nil {
		return Artifact{}, err
	}
	art.Target = TargetWindowsNSIS
	return art, nil
}

func nsisEscape(s string) string {
	return strings.ReplaceAll(s, `"`, `'`)
}
