// Package bindings generates Phase 3 TypeScript frontend stubs from command
// and event definitions. Output is deterministic and tied to the kernel API
// version.
package bindings

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"go.klarlabs.de/vitra/domain"
)

// GenerateTypeScript emits a TypeScript module for the given commands and
// optional event names (plugin Contribution.Events / runtime channels).
func GenerateTypeScript(moduleName, kernelVersion string, commands []*domain.CommandDefinition, events []domain.EventName) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by vitra bindings. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// kernel: %s\n", kernelVersion)
	fmt.Fprintf(&b, "// module: %s\n\n", moduleName)
	b.WriteString("export type VitraInvoker = (command: string, input?: unknown, resourcePath?: string) => Promise<unknown>;\n")
	b.WriteString("export type VitraEventHandler = (payload: unknown) => void;\n")
	b.WriteString("export type VitraSubscriber = (event: string, handler: VitraEventHandler) => () => void;\n\n")
	b.WriteString("export interface VitraClient {\n")
	sorted := append([]*domain.CommandDefinition(nil), commands...)
	sort.Slice(sorted, func(i, j int) bool {
		return string(sorted[i].Name()) < string(sorted[j].Name())
	})
	for _, c := range sorted {
		if c == nil {
			continue
		}
		method := tsMethodName(string(c.Name()))
		fmt.Fprintf(&b, "  /** %s — requires permission `%s` */\n", c.Description(), c.Permission())
		fmt.Fprintf(&b, "  %s(input?: unknown, resourcePath?: string): Promise<unknown>;\n", method)
	}
	b.WriteString("}\n\n")
	b.WriteString("export function createClient(invoke: VitraInvoker): VitraClient {\n")
	b.WriteString("  return {\n")
	for _, c := range sorted {
		if c == nil {
			continue
		}
		method := tsMethodName(string(c.Name()))
		fmt.Fprintf(&b, "    %s: (input, resourcePath) => invoke(%q, input, resourcePath),\n", method, c.Name())
	}
	b.WriteString("  };\n}\n")

	evSorted := uniqueSortedEvents(events)
	if len(evSorted) > 0 {
		b.WriteString("\nexport interface VitraEvents {\n")
		for _, ev := range evSorted {
			method := tsEventMethodName(string(ev))
			fmt.Fprintf(&b, "  /** Subscribe to `%s` via vitra.on; returns an unsubscribe function. */\n", ev)
			fmt.Fprintf(&b, "  %s(handler: VitraEventHandler): () => void;\n", method)
		}
		b.WriteString("}\n\n")
		b.WriteString("export function createEvents(on: VitraSubscriber): VitraEvents {\n")
		b.WriteString("  return {\n")
		for _, ev := range evSorted {
			method := tsEventMethodName(string(ev))
			fmt.Fprintf(&b, "    %s: (handler) => on(%q, handler),\n", method, ev)
		}
		b.WriteString("  };\n}\n")
	}
	return b.String()
}

func uniqueSortedEvents(events []domain.EventName) []domain.EventName {
	seen := map[string]struct{}{}
	var out []domain.EventName
	for _, ev := range events {
		s := string(ev)
		if s == "" {
			continue
		}
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, ev)
	}
	sort.Slice(out, func(i, j int) bool {
		return string(out[i]) < string(out[j])
	})
	return out
}

func tsMethodName(command string) string {
	parts := strings.FieldsFunc(command, func(r rune) bool {
		return r == '.' || r == '-' || r == '_'
	})
	if len(parts) == 0 {
		return "invoke"
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(strings.ToLower(p[:1]) + p[1:])
			continue
		}
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

func tsEventMethodName(event string) string {
	return "on" + strings.ToUpper(tsMethodName(event)[:1]) + tsMethodName(event)[1:]
}
