// Package bindings generates Phase 3 TypeScript frontend stubs from command
// definitions. Output is deterministic and tied to the kernel API version.
package bindings

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"go.klarlabs.de/vitra/domain"
)

// GenerateTypeScript emits a minimal TypeScript module for the given commands.
func GenerateTypeScript(moduleName, kernelVersion string, commands []*domain.CommandDefinition) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by vitra bindings. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// kernel: %s\n", kernelVersion)
	fmt.Fprintf(&b, "// module: %s\n\n", moduleName)
	b.WriteString("export type VitraInvoker = (command: string, input?: unknown, resourcePath?: string) => Promise<unknown>;\n\n")
	b.WriteString("export interface VitraClient {\n")
	sorted := append([]*domain.CommandDefinition(nil), commands...)
	sort.Slice(sorted, func(i, j int) bool {
		return string(sorted[i].Name()) < string(sorted[j].Name())
	})
	for _, c := range sorted {
		if c == nil {
			continue
		}
		method := tsMethodName(string(c.Name()))
		fmt.Fprintf(&b, "  /** %s — requires permission `%s` */\n", c.Description(), c.Permission())
		fmt.Fprintf(&b, "  %s(input?: unknown, resourcePath?: string): Promise<unknown>;\n", method)
	}
	b.WriteString("}\n\n")
	b.WriteString("export function createClient(invoke: VitraInvoker): VitraClient {\n")
	b.WriteString("  return {\n")
	for _, c := range sorted {
		if c == nil {
			continue
		}
		method := tsMethodName(string(c.Name()))
		fmt.Fprintf(&b, "    %s: (input, resourcePath) => invoke(%q, input, resourcePath),\n", method, c.Name())
	}
	b.WriteString("  };\n}\n")
	return b.String()
}

func tsMethodName(command string) string {
	parts := strings.FieldsFunc(command, func(r rune) bool {
		return r == '.' || r == '-' || r == '_'
	})
	if len(parts) == 0 {
		return "invoke"
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(strings.ToLower(p[:1]) + p[1:])
			continue
		}
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
